# Generated by Django 6.0.5 on 2026-06-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_05b4bc_idx',
            old_name='notification_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_is_read_9edb86_idx',
            old_name='notification_is_read_idx',
        ),
    ]
