# Generated by Django 6.0.5 on 2026-06-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('order_type', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], default='delivery', max_length=10)),
                ('delivery_address', models.TextField(blank=True)),
                ('order_notes', models.TextField(blank=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('paytrail_stamp', models.CharField(blank=True, max_length=200)),
                ('paytrail_tx_id', models.CharField(blank=True, max_length=200)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_name', models.CharField(max_length=200)),
                ('menu_item_name_fi', models.CharField(blank=True, max_length=200)),
                ('quantity', models.IntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('special_instruction', models.TextField(blank=True, help_text='e.g. No onions, Extra spicy')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemSelectedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_name', models.CharField(max_length=100)),
                ('extra_name_fi', models.CharField(blank=True, max_length=100)),
                ('option_name', models.CharField(max_length=100)),
                ('option_name_fi', models.CharField(blank=True, max_length=100)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
