# Generated by Django 6.0.5 on 2026-06-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
    ]
