# Generated by Django 6.0.5 on 2026-06-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online (Paytrail)'), ('cash_on_delivery', 'Cash on Delivery'), ('card_on_delivery', 'Card on Delivery')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
