# Generated by Django 6.0.5 on 2026-05-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_update_order_and_items'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitemspecialrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orderitemspecialrequest',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='orderitemtopping',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='paytrail_stamp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='paytrail_tx_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item_name_fi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='special_instruction',
            field=models.TextField(blank=True, help_text='e.g. No onions, Extra spicy'),
        ),
        migrations.DeleteModel(
            name='OrderItemSeasoning',
        ),
        migrations.DeleteModel(
            name='OrderItemSpecialRequest',
        ),
        migrations.DeleteModel(
            name='OrderItemTopping',
        ),
    ]
