# Generated by Django 6.0.5 on 2026-06-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online (Paytrail)'), ('cash_on_delivery', 'Cash on Delivery'), ('cash_on_pickup', 'Cash on Pickup')], default='online', max_length=20),
        ),
    ]
