# Generated by Django 6.0.5 on 2026-06-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_pickup_time',
            field=models.DateTimeField(blank=True, help_text='Customer requested pickup time (pickup orders only)', null=True),
        ),
    ]
