# Generated by Django 6.0.5 on 2026-06-03 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ravintola Amazona', max_length=200)),
                ('address', models.TextField(default='Aleksanterinkatu 3, 15110 Lahti, Finland')),
                ('phone', models.CharField(default='+358037333366', max_length=20)),
                ('phone_2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(default='info@ravintolaamazona.fi', max_length=254)),
                ('latitude', models.FloatField(default=60.9827)),
                ('longitude', models.FloatField(default=25.6612)),
                ('is_delivery_enabled', models.BooleanField(default=True)),
                ('free_delivery_radius_km', models.PositiveIntegerField(default=9)),
                ('paid_delivery_radius_km', models.PositiveIntegerField(default=14)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('min_order', models.DecimalField(decimal_places=2, default=13.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'Restaurant Settings',
                'verbose_name_plural': 'Restaurant Settings',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('is_closed', models.BooleanField(default=False)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('lunch_open', models.TimeField(blank=True, null=True)),
                ('lunch_close', models.TimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='restaurant.restaurantsettings')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('restaurant', 'day')},
            },
        ),
    ]
