# Generated by Django 6.0.5 on 2026-06-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_paytrai_2778c1_idx',
            old_name='payments_payment_stamp_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_status_7ad4af_idx',
            old_name='payments_payment_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_created_b8a300_idx',
            old_name='payments_payment_created_idx',
        ),
    ]
