# Generated by Django 6.0.5 on 2026-05-30 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('name_fi', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_fi', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
                ('has_deal', models.BooleanField(default=False)),
                ('deal_label', models.CharField(blank=True, help_text='e.g. "2 Pizzas + Drink = €19.90"', max_length=200)),
                ('deal_label_fi', models.CharField(blank=True, max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('name_fi', models.CharField(blank=True, max_length=100)),
                ('extra_type', models.CharField(choices=[('choice', 'Single Choice (Size, Sauce, Spice Level)'), ('extra', 'Multiple Selection (Toppings, Add-ons)')], default='choice', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=False, help_text='Customer must select this before adding to cart')),
                ('max_selections', models.IntegerField(blank=True, help_text='Max options selectable (for multiple type only). Leave blank for unlimited.', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='menu.category')),
            ],
            options={
                'verbose_name_plural': 'Extras',
                'ordering': ['category', 'order'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('name_fi', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_fi', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, help_text='Regular price', max_digits=6)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price. Agar set hai toh base price ki jagah yeh show hoga', max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_menu_item', models.BooleanField(default=True)),
                ('is_lunch_item', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExtraOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('name_fi', models.CharField(blank=True, max_length=100)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, help_text='Extra cost on top of item base price', max_digits=6)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price for this option. If set, shown instead of additional_price', max_digits=6, null=True)),
                ('order', models.IntegerField(default=0)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.extra')),
            ],
            options={
                'ordering': ['extra', 'order'],
                'unique_together': {('extra', 'name')},
            },
        ),
    ]
