# Generated by Django 6.0.5 on 2026-05-28 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('name_fi', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_fi', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('name_fi', models.CharField(blank=True, max_length=100)),
                ('extra_type', models.CharField(choices=[('choice', 'Single Choice (Size, Sauce, Spice Level, etc.)'), ('extra', 'Multiple Extra (Toppings, Add-ons, etc.)')], default='choice', help_text='Select "choice" for single selection like Size, "extra" for multiple selections like Toppings', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order in the Add Item page')),
                ('is_required', models.BooleanField(default=False, help_text='Customers must select this before adding to cart')),
                ('max_selections', models.IntegerField(blank=True, help_text='Max options selectable (only for "extra" type). Leave blank for unlimited.', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='menu.category')),
            ],
            options={
                'verbose_name_plural': 'Extras',
                'ordering': ['category', 'order'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('name_fi', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_fi', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_menu_item', models.BooleanField(default=True)),
                ('is_lunch_item', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExtraOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('name_fi', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price. If set, will be displayed instead of regular price', max_digits=6, null=True)),
                ('order', models.IntegerField(default=0)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.extra')),
            ],
            options={
                'ordering': ['extra', 'order'],
                'unique_together': {('extra', 'name')},
            },
        ),
    ]
