# Generated by Django 6.0.5 on 2026-06-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraoption',
            name='is_default',
            field=models.BooleanField(default=False, help_text='This option will be selected by default when adding the extra to the cart'),
        ),
    ]
