# Generated by Django 6.0.5 on 2026-06-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_extraoption_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraoption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this option to customers'),
        ),
    ]
