# Generated by Django 6.0.5 on 2026-06-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_extraoption_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='min_selections',
            field=models.IntegerField(default=0, help_text='Minimum options customer must select (0 = optional)'),
        ),
    ]
