# Generated by Django 6.0.5 on 2026-06-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_extra_min_selections'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this extra group to customers'),
        ),
    ]
